#!/usr/bin/env python3
# sonar_to_costmap.py
# ################################################################################
# edited WHS, OJ , 23.12.2020 #
#
# brings Sonar detected Obstacles into move_base local costmap
# using point_cloud - message
#
# edit
# real Bot
# edit costmap_common_params_burger.yaml
#    observation_sources: scan sonar
#    scan: ...
#    sonar: {sensor_frame: base_link, data_type: PointCloud,
#             topic: /sonar/point_cloud, marking: true, clearing: true}
#
# edit move_base.launch  => /cmd_vel to /move_base/cmd_vel
#     <arg name="cmd_vel_topic" default="/move_base/cmd_vel" />
#
# usage
#   $2 roslaunch turtlebot3_navigation turtlebot3_navigation.launch
#                map_file:=$HOME/catkin_ws/src/rtc/rtc_maps/gazebo_house_map_2020_12_07.yaml
#   $3 roslaunch rtc sonar_twist_mux.launch
#   ggf. sudo apt-get install ros-noetic-twist-mux*
#   $4 rosrun rtc sonar_obstacle_avoidance.py
#   $5 rosrun rtc sonar_to_costmap.py
# ------------------------------------------------------------------

import rospy
import std_msgs.msg
from geometry_msgs.msg import Point32
# from sensor_msgs.msg import Range
from sensor_msgs.msg import PointCloud
from turtlebot3_msgs.msg import SensorState


class Sonar_to_Point_Cloud():
    def __init__(self):
        rospy.loginfo("Publishing PointCloud")

        self.cloud_pub = rospy.Publisher('sonar/point_cloud',
                                         PointCloud,
                                         queue_size=10)

        # receiving sonar_left and sonar_right
        self.sensor_sub = rospy.Subscriber('sensor_state', SensorState,
                                           self.get_sonar, queue_size=10)

        self.dist_left = 0.0
        self.dist_right = 0.0
        self.rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            self.rate.sleep()

    def get_sonar(self, sensor_data):
        # rospy.loginfo(" Sensor Data received ")
        self.dist_left = sensor_data.cliff / 100.0  # cm in m
        rospy.loginfo(" Sonar Data Left %f", self.dist_left)
        self.dist_right = sensor_data.sonar / 100.0  # cm in m
        rospy.loginfo(" Sonar Data Right %f", self.dist_right)
        self.cloud_build()

    def cloud_build(self):
        # add sonar readings (robot-local coordinate frame) to cloud
        pl = Point32()
        pr = Point32()
        # Instanziiere leere PointCloud
        cloud = PointCloud()
        # filling pointcloud header
        header = std_msgs.msg.Header()
        header.stamp = rospy.Time.now()
        header.frame_id = 'base_link'
        cloud.header = header

        # Linke Seite
        if(self.dist_left < 2.00 and self.dist_left > 0.03):
            pl.x = self.dist_left
            pl.y = 0.09
            pl.z = 0.0
            cloud.points.append(pl)

        # Rechte Seite  punkt einfügen  (x,y,z)
        if(self.dist_right < 2.00 and self.dist_right > 0.03):
            pr.x = self.dist_right
            pr.y = -0.09
            pr.z = 0.0
            cloud.points.append(pr)

        # Linie aus 10 Punkten zeichnen
        dx = (pr.x - pl.x) / 10
        dy = (pr.y - pl.y) / 10
        i = 0
        # rospy.loginfo(" dx %f  dy %f ", dx, dy)
        while i < 9:
            i = i + 1
            pm = Point32()
            pm.x = pl.x + i * dx
            pm.y = pl.y + i * dy
            cloud.points.append(pm)
            rospy.loginfo(" Point Nr. %d %f %f appended ", i, pm.x, pm.y)

        # Senden
        self.cloud_pub.publish(cloud)


if __name__ == '__main__':
    rospy.init_node('sonar_controller', anonymous=True)
    try:
        sonar = Sonar_to_Point_Cloud()
    except rospy.ROSInterruptException:
        pass
